const menujson = [{
    id: 1,
    name: "Arepa de choclo",
    value: 7000,
    description: "Rociado con miel acompañada con queso cuajada",
    category: "Entrada",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 2,
    name: "Patacones o arepas montadas con carne desmechada",
    value: 13500,
    description: "(3 unidades) con hogao, acompañado con salsa de la casa y mayonesa de ajo",
    category: "Entrada",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 3,
    name: "Patacones o arepas montadas con pollo desmechada",
    value: 12000,
    description: "(3 unidades) con hogao, acompañado con salsa de la casa y mayonesa de ajo",
    category: "Entrada",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 4,
    name: "Arepas o patacones",
    value: 5000,
    description: "(3 unidades) acompañado con hogao",
    category: "Entrada",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 5,
    name: "Chorizo",
    value: 12000,
    description: "(2 unidades) con cascos de limón y tomate, acompañado con patacón o arepa y chimichurri",
    category: "Entrada",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 6,
    name: "Crispetas de pollo",
    value: 12000,
    description: "(2 unidades) con cascos de limón y tomate, acompañado con patacón o arepa y chimichurri",
    category: "Entrada",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 7,
    name: "Parrillada familiar",
    value: 95000,
    description: "Costilla y espinazo de cerdo en salsa bbq, crispeta de pollo, punta de anca, chorizo, chicharrón, arepas, chips de plátano verde, acompañado con salsa de la casa, salsa rosada y chimichurri",
    category: "Platos Fuertes",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 8,
    name: "Media parrillada",
    value: 55000,
    description: "Costilla y espinazo de cerdo en salsa bbq, crispeta de pollo, punta de anca, chorizo, chicharrón, arepas, chips de plátano verde, acompañado con salsa de la casa, salsa rosada y chimichurri",
    category: "Platos Fuertes",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 9,
    name: "Churrasco",
    value: 37000,
    description: "Acompañado con papa hasselback, arepa, vegetales al carbón, mayonesa de ajo y chimichurri",
    category: "Platos Fuertes",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 10,
    name: "Churrasco de pollo",
    value: 18000,
    description: "Acompañado con papas ala francesa, arepa, vegetales al carbón y salsa rosada",
    category: "Platos Fuertes",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 11,
    name: "Punta de anca",
    value: 37000,
    description: "Acompañado con papa hasselback, arepa, vegetales al carbón, mayonesa de ajo y chimichurri",
    category: "Platos Fuertes",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 12,
    name: "Solomito",
    value: 39000,
    description: "Acompañado con papa hasselback, arepa, vegetales al carbón, mayonesa de ajo y chimichurri",
    category: "Platos Fuertes",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 13,
    name: "Chicharrón",
    value: 18000,
    description: "Acompañado con patacón o arepa, cascos de limón, mayonesa de ajo y chimichurri",
    category: "Platos Fuertes",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 14,
    name: "Costillas BBQ",
    value: 22000,
    description: "Acompañado con papa a la francesa, arepa y mayonesa de ajo",
    category: "Platos Fuertes",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 15,
    name: "Pechuga a la plancha",
    value: 22000,
    description: "Acompañado de papas a la francesa, vegetales al carbón, salsa de la casa y miel mostaza",
    category: "Platos Fuertes",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 16,
    name: "Casuela de frijoles",
    value: 16000,
    description: "Con chicharrón, chirizo, carne desmecha y hogao, acompañado de arroz blanco, arepa y tajadadura",
    category: "Platos Fuertes",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 16,
    name: "Pal'tajo",
    value: 15500,
    description: "Calentado tradicional, acompañado con tortilla de huevo, carne desmechada, platano madur arepa",
    category: "Platos Fuertes",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 17,
    name: "Hamgurguesa Rústika",
    value: 15000,
    description: "Pan, carne artesanal 200 gr, pepino agridulce, cebolla grille, queso mozarela, salsa de maíz, tocineta, tomate, lechuga, plátano maduro, acompañado  con papa a la francesa y salsa de la casa",
    category: "Platos Fuertes",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 18,
    name: "Hamgurguesa de pollo",
    value: 16000,
    description: "Pan, pechuga de pollo, cebolla grille, queso mozarela, salsa de maíz, tocineta, tomate, lechuga, acompañado  con papa a la francesa y salsa de la casa",
    category: "Platos Fuertes",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 19,
    name: "Trucha Rústika",
    value: 16000,
    description: "En salsa de encocado, acompañado con julianas de vegetal salteado y patacones",
    category: "Platos Fuertes",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 20,
    name: "Sancocho de espinazo",
    value: 10000,
    description: "Acompañado con arroz, arepa y pico de gallo",
    category: "Platos Fuertes",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 21,
    name: "Arepa",
    value: 2000,
    description: "3 unidades",
    category: "Adiciones",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 22,
    name: "Arroz blanco",
    value: 3000,
    description: "120 gramos",
    category: "Adiciones",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 23,
    name: "Carne desmechada",
    value: 6000,
    description: "60 gramos",
    category: "Adiciones",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 24,
    name: "Chicharron",
    value: 6000,
    description: "300 gramos",
    category: "Adiciones",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 25,
    name: "Chips de platano",
    value: 2000,
    description: "100 gramos",
    category: "Adiciones",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 26,
    name: "Chorizo",
    value: 4500,
    description: "1 unidad",
    category: "Adiciones",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 27,
    name: "Frijol",
    value: 4000,
    description: "250 gramos",
    category: "Adiciones",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 28,
    name: "Maicitos",
    value: 3000,
    description: "50 gramos",
    category: "Adiciones",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 29,
    name: "Papas a la francesa",
    value: 4500,
    description: "100 gramos",
    category: "Adiciones",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 29,
    name: "Papas Hasselback",
    value: 2000,
    description: "1 unidad",
    category: "Adiciones",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 30,
    name: "Patacones",
    value: 4000,
    description: "1 unidad",
    category: "Adiciones",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 31,
    name: "Pollo desmechado",
    value: 5000,
    description: "60 gramos",
    category: "Adiciones",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 32,
    name: "Queso cuajada",
    value: 2500,
    description: "90 gramos",
    category: "Adiciones",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 33,
    name: "Tajada madura",
    value: 2000,
    description: "70 gramos",
    category: "Adiciones",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 34,
    name: "Tostada",
    value: 650,
    description: "1 unidad",
    category: "Adiciones",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 35,
    name: "Vegetales al carbón",
    value: 4800,
    description: "150 gramos",
    category: "Adiciones",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 36,
    name: "Rústika",
    value: 19000,
    description: "Pechuga de pollo, lechuga crespa, maicitos, tomate, apio dulce, crotones y aderezo de vinagre balsámico",
    category: "Ensaladas",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 37,
    name: "Salteado vegano",
    value: 14000,
    description: "Maicitos, champiñones, apio dulce, zuccini, pimentón, aderezo de vinagre balsámico, acompañado de arroz con maní tostado",
    category: "Ensaladas",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 38,
    name: "Brownie con helado",
    value: 8000,
    description: "",
    category: "Postres",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 39,
    name: "Brownie",
    value: 5000,
    description: "",
    category: "Postres",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 40,
    name: "Canelones de banano",
    value: 5500,
    description: "",
    category: "Postres",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 41,
    name: "Cheese cake",
    value: 7000,
    description: "",
    category: "Postres",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 42,
    name: "Copa de helado",
    value: 6500,
    description: "",
    category: "Postres",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 43,
    name: "Sanduche de helado",
    value: 12500,
    description: "",
    category: "Postres",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 44,
    name: "Sanduche de helado",
    value: 12500,
    description: "",
    category: "Postres",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 45,
    name: "Americano",
    valueUnit: 1500,
    valueJug: 0,
    description: "",
    category: "Bebidas calientes",
    subCategory: "Café",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 46,
    name: "Bombon",
    valueUnit: 5000,
    valueJug: 0,
    description: "Expreso, leche condensada y chantilly",
    category: "Bebidas calientes",
    subCategory: "Café",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 47,
    name: "Cappucino",
    valueUnit: 4000,
    valueJug: 0,
    description: "",
    category: "Bebidas calientes",
    subCategory: "Café",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 48,
    name: "Cappucino con Amaretto",
    valueUnit: 7000,
    valueJug: 0,
    description: "",
    category: "Bebidas calientes",
    subCategory: "Café",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 49,
    name: "Cappucino con Crema de Whisky",
    valueUnit: 8500,
    valueJug: 0,
    description: "",
    category: "Bebidas calientes",
    subCategory: "Café",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 50,
    name: "Carajillo",
    valueUnit: 6000,
    valueJug: 0,
    description: "con Aguardiente, Brandy o Ron",
    category: "Bebidas calientes",
    subCategory: "Café",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 51,
    name: "Irlandés",
    valueUnit: 9000,
    valueJug: 0,
    description: "Black and White, expresso y chantilly",
    category: "Bebidas calientes",
    subCategory: "Café",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 52,
    name: "De Bosal",
    valueUnit: 1500,
    valueJug: 0,
    description: "",
    category: "Bebidas calientes",
    subCategory: "Aromaticas",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 53,
    name: "De Panela",
    valueUnit: 1500,
    valueJug: 0,
    description: "",
    category: "Bebidas calientes",
    subCategory: "Aromaticas",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 54,
    name: "Frutos Amarillos",
    valueUnit: 4000,
    valueJug: 0,
    description: "Mango, piña y maracuya",
    category: "Bebidas calientes",
    subCategory: "Aromaticas naturales",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 54,
    name: "Frutos Rojos",
    valueUnit: 4000,
    valueJug: 0,
    description: "Fresa y mora",
    category: "Bebidas calientes",
    subCategory: "Aromaticas naturales",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 55,
    name: "Hierbabuena",
    valueUnit: 1500,
    valueJug: 0,
    description: "",
    category: "Bebidas calientes",
    subCategory: "Aromaticas naturales",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 55,
    name: "Primavera",
    valueUnit: 5000,
    valueJug: 0,
    description: "Piña, jengibre, tomate de árbol y naranja",
    category: "Bebidas calientes",
    subCategory: "Aromaticas de frutos secos",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 56,
    name: "Tradicional",
    valueUnit: 5000,
    valueJug: 0,
    description: "Piña, coco, mango, arándano y flor de Jamaica",
    category: "Bebidas calientes",
    subCategory: "Aromaticas de frutos secos",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 56,
    name: "Frutos Rojos",
    valueUnit: 5000,
    valueJug: 0,
    description: "Fresa, mora, arándano y flor de Jamaica",
    category: "Bebidas calientes",
    subCategory: "Aromaticas de frutos secos",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 57,
    name: "Frutos Amarillos",
    valueUnit: 5000,
    valueJug: 0,
    description: "Piña, maracuyá, banano, mango y naranja",
    category: "Bebidas calientes",
    subCategory: "Aromaticas de frutos secos",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 58,
    name: "Frutos Amarillos",
    valueUnit: 5000,
    valueJug: 0,
    description: "Piña, maracuyá, banano, mango y naranja",
    category: "Bebidas calientes",
    subCategory: "Aromaticas de frutos secos",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 59,
    name: "Chocolate con queso",
    valueUnit: 4000,
    valueJug: 0,
    description: "",
    category: "Bebidas calientes",
    subCategory: "Chocolate",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 59,
    name: "Chocolate con leche y queso",
    valueUnit: 5500,
    valueJug: 0,
    description: "",
    category: "Bebidas calientes",
    subCategory: "Chocolate",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 60,
    name: "Chocolate con Chantilly",
    valueUnit: 6000,
    valueJug: 0,
    description: "",
    category: "Bebidas calientes",
    subCategory: "Chocolate",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 61,
    name: "Chocolate con masmelos",
    valueUnit: 5500,
    valueJug: 0,
    description: "",
    category: "Bebidas calientes",
    subCategory: "Chocolate",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 176,
    name: "Natural",
    valueUnit: 4000,
    valueJug: 0,
    description: "Maracuyá, naranja, hierbabuena, canela y panela",
    category: "Bebidas calientes",
    subCategory: "Canelazo",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 177,
    name: "Con licor (Aguardiente, Brandy o Ron)",
    valueUnit: 7500,
    valueJug: 0,
    description: "Maracuyá, naranja, hierbabuena, canela y panela",
    category: "Bebidas calientes",
    subCategory: "Canelazo",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 175,
    name: "Colada tradicional",
    valueUnit: 5000,
    valueJug: 0,
    description: "",
    category: "Bebidas calientes",
    subCategory: "Otras bebidas calientes",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 62,
    name: "Agua Panela con queso",
    valueUnit: 3500,
    valueJug: 0,
    description: "",
    category: "Bebidas calientes",
    subCategory: "Otras bebidas calientes",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 63,
    name: "Milo",
    valueUnit: 4500,
    valueJug: 0,
    description: "",
    category: "Bebidas calientes",
    subCategory: "Otras bebidas calientes",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 64,
    name: "Milito",
    valueUnit: 2500,
    valueJug: 0,
    description: "",
    category: "Bebidas calientes",
    subCategory: "Otras bebidas calientes",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 65,
    name: "Soda frutos amarillos",
    valueUnit: 6000,
    valueJug: 22000,
    description: "",
    category: "Bebidas frias",
    subCategory: "Sodas saborizadas",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 66,
    name: "Soda frutos rojos",
    valueUnit: 6000,
    valueJug: 22000,
    description: "",
    category: "Bebidas frias",
    subCategory: "Sodas saborizadas",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 67,
    name: "Granizado de Frutos Amarillos",
    valueUnit: 5500,
    valueJug: 20000,
    description: "",
    category: "Bebidas frias",
    subCategory: "Granizados",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 68,
    name: "Granizado de Frutos Rojos",
    valueUnit: 5500,
    valueJug: 20000,
    description: "",
    category: "Bebidas frias",
    subCategory: "Granizados",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 69,
    name: "Malteada de Mora",
    valueUnit: 9000,
    valueJug: 0,
    description: "",
    category: "Bebidas frias",
    subCategory: "Malteadas",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 70,
    name: "Malteada de Fresa",
    valueUnit: 9000,
    valueJug: 0,
    description: "",
    category: "Bebidas frias",
    subCategory: "Malteadas",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 71,
    name: "Malteada de Mango",
    valueUnit: 9000,
    valueJug: 0,
    description: "",
    category: "Bebidas frias",
    subCategory: "Malteadas",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 72,
    name: "Malteada de Maracuyá",
    valueUnit: 9000,
    valueJug: 0,
    description: "",
    category: "Bebidas frias",
    subCategory: "Malteadas",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 73,
    name: "Malteada de Oreo",
    valueUnit: 9000,
    valueJug: 0,
    description: "",
    category: "Bebidas frias",
    subCategory: "Malteadas",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 74,
    name: "Fresa en agua",
    valueUnit: 4000,
    valueJug: 14000,
    description: "",
    category: "Bebidas frias",
    subCategory: "Jugos Naturales",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 75,
    name: "Fresa en leche",
    valueUnit: 5000,
    valueJug: 18000,
    description: "",
    category: "Bebidas frias",
    subCategory: "Jugos Naturales",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 76,
    name: "Mango en agua",
    valueUnit: 4000,
    valueJug: 14000,
    description: "",
    category: "Bebidas frias",
    subCategory: "Jugos Naturales",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 77,
    name: "Mango en leche",
    valueUnit: 5000,
    valueJug: 18000,
    description: "",
    category: "Bebidas frias",
    subCategory: "Jugos Naturales",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 78,
    name: "Piña en agua",
    valueUnit: 4000,
    valueJug: 14000,
    description: "",
    category: "Bebidas frias",
    subCategory: "Jugos Naturales",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 79,
    name: "Piña en leche",
    valueUnit: 5000,
    valueJug: 18000,
    description: "",
    category: "Bebidas frias",
    subCategory: "Jugos Naturales",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 80,
    name: "Guanábana en agua",
    valueUnit: 4000,
    valueJug: 14000,
    description: "",
    category: "Bebidas frias",
    subCategory: "Jugos Naturales",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 81,
    name: "Guanábana en leche",
    valueUnit: 5000,
    valueJug: 18000,
    description: "",
    category: "Bebidas frias",
    subCategory: "Jugos Naturales",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 82,
    name: "Maracuyá en agua",
    valueUnit: 4000,
    valueJug: 14000,
    description: "",
    category: "Bebidas frias",
    subCategory: "Jugos Naturales",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 83,
    name: "Maracuyá en leche",
    valueUnit: 5000,
    valueJug: 18000,
    description: "",
    category: "Bebidas frias",
    subCategory: "Jugos Naturales",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 84,
    name: "Lulo en agua",
    valueUnit: 4000,
    valueJug: 14000,
    description: "",
    category: "Bebidas frias",
    subCategory: "Jugos Naturales",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 85,
    name: "Lulo en leche",
    valueUnit: 5000,
    valueJug: 18000,
    description: "",
    category: "Bebidas frias",
    subCategory: "Jugos Naturales",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 86,
    name: "Mora en agua",
    valueUnit: 4000,
    valueJug: 14000,
    description: "",
    category: "Bebidas frias",
    subCategory: "Jugos Naturales",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 87,
    name: "Mora en leche",
    valueUnit: 5000,
    valueJug: 18000,
    description: "",
    category: "Bebidas frias",
    subCategory: "Jugos Naturales",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 87,
    name: "Colombiana",
    valueUnit: 3500,
    valueJug: 0,
    description: "",
    category: "Bebidas frias",
    subCategory: "Gaseosas",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 88,
    name: "Manzana",
    valueUnit: 3500,
    valueJug: 0,
    description: "",
    category: "Bebidas frias",
    subCategory: "Gaseosas",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 89,
    name: "Naranja",
    valueUnit: 3500,
    valueJug: 0,
    description: "",
    category: "Bebidas frias",
    subCategory: "Gaseosas",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 90,
    name: "Tamarindo",
    valueUnit: 3500,
    valueJug: 0,
    description: "",
    category: "Bebidas frias",
    subCategory: "Gaseosas",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 91,
    name: "Coca Cola",
    valueUnit: 3500,
    valueJug: 0,
    description: "",
    category: "Bebidas frias",
    subCategory: "Gaseosas",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 92,
    name: "Coca Cola Zero",
    valueUnit: 3500,
    valueJug: 0,
    description: "",
    category: "Bebidas frias",
    subCategory: "Gaseosas",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 93,
    name: "Natural",
    valueUnit: 4000,
    valueJug: 14000,
    description: "",
    category: "Bebidas frias",
    subCategory: "Limonadas",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 94,
    name: "Hierbabuena",
    valueUnit: 5000,
    valueJug: 18000,
    description: "",
    category: "Bebidas frias",
    subCategory: "Limonadas",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 95,
    name: "De Mango Biche",
    valueUnit: 5000,
    valueJug: 15000,
    description: "",
    category: "Bebidas frias",
    subCategory: "Limonadas",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 96,
    name: "La Bogadera",
    valueUnit: 5000,
    valueJug: 18000,
    description: "",
    category: "Bebidas frias",
    subCategory: "Limonadas",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 97,
    name: "De Coco",
    valueUnit: 6500,
    valueJug: 0,
    description: "",
    category: "Bebidas frias",
    subCategory: "Limonadas",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 98,
    name: "Águila Light",
    valueUnit: 5000,
    valueJug: 0,
    description: "-Michelada Tradicional $1000" +
        "-Michelada con mango Biche $2000" +
        "-Michelada con Maracuyá $1400",
    category: "Bebidas frias",
    subCategory: "Cervezas",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 99,
    name: "Póker",
    valueUnit: 4500,
    valueJug: 0,
    description: "-Michelada Tradicional $1000" +
        "-Michelada con mango Biche $2000" +
        "-Michelada con Maracuyá $1400",
    category: "Bebidas frias",
    subCategory: "Cervezas",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 100,
    name: "Club Dorada",
    valueUnit: 5500,
    valueJug: 0,
    description: "-Michelada Tradicional $1000" +
        "-Michelada con mango Biche $2000" +
        "-Michelada con Maracuyá $1400",
    category: "Bebidas frias",
    subCategory: "Cervezas",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 101,
    name: "Club Roja",
    valueUnit: 5500,
    valueJug: 0,
    description: "-Michelada Tradicional $1000" +
        "-Michelada con mango Biche $2000" +
        "-Michelada con Maracuyá $1400",
    category: "Bebidas frias",
    subCategory: "Cervezas",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 102,
    name: "Club Negra",
    valueUnit: 5500,
    valueJug: 0,
    description: "-Michelada Tradicional $1000" +
        "-Michelada con mango Biche $2000" +
        "-Michelada con Maracuyá $1400",
    category: "Bebidas frias",
    subCategory: "Cervezas",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 103,
    name: "Corona",
    valueUnit: 8000,
    valueJug: 0,
    description: "-Michelada Tradicional $1000" +
        "-Michelada con mango Biche $2000" +
        "-Michelada con Maracuyá $1400",
    category: "Bebidas frias",
    subCategory: "Cervezas",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 104,
    name: "Coronita",
    valueUnit: 5000,
    valueJug: 0,
    description: "-Michelada Tradicional $1000" +
        "-Michelada con mango Biche $2000" +
        "-Michelada con Maracuyá $1400",
    category: "Bebidas frias",
    subCategory: "Cervezas",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 105,
    name: "Aguan en botella Cristal",
    valueUnit: 3000,
    valueJug: 0,
    description: "",
    category: "Bebidas frias",
    subCategory: "Otras bebidas frias",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 106,
    name: "Agua con gas Cristal",
    valueUnit: 4000,
    valueJug: 0,
    description: "",
    category: "Bebidas frias",
    subCategory: "Otras bebidas frias",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 107,
    name: "Agua en en botella Manantial",
    valueUnit: 4000,
    valueJug: 0,
    description: "",
    category: "Bebidas frias",
    subCategory: "Otras bebidas frias",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 108,
    name: "Milo frio",
    valueUnit: 4500,
    valueJug: 0,
    description: "",
    category: "Bebidas frias",
    subCategory: "Otras bebidas frias",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 109,
    name: "Chocolate frio",
    valueUnit: 6500,
    valueJug: 0,
    description: "",
    category: "Bebidas frias",
    subCategory: "Otras bebidas frias",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 110,
    name: "Red bull",
    valueUnit: 8500,
    valueJug: 0,
    description: "",
    category: "Bebidas frias",
    subCategory: "Otras bebidas frias",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 111,
    name: "Soda",
    valueUnit: 4500,
    valueJug: 0,
    description: "",
    category: "Bebidas frias",
    subCategory: "Otras bebidas frias",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 112,
    name: "Tónica Premium",
    valueUnit: 15000,
    valueJug: 0,
    description: "",
    category: "Bebidas frias",
    subCategory: "Otras bebidas frias",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 113,
    name: "Margarita Tradicional",
    valueUnit: 15000,
    valueJug: 0,
    description: "José Cuervo, Triple Sec, zumo de limón y michelada con sal aromatizada de la casa",
    category: "Cocteleria",
    subCategory: "Margaritas",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 114,
    name: "Margarita Picante",
    valueUnit: 15000,
    valueJug: 0,
    description: "José Cuervo, Triple Sec, zumo de limón, reducción de chiles y michelada con sal aromatizada de la casa",
    category: "Cocteleria",
    subCategory: "Margaritas",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 115,
    name: "Margarita de Café",
    valueUnit: 25000,
    valueJug: 0,
    description: "Patron XO Café, Triple Sec, Amaretto, zumo de limón y michelada con sal aromatizada de la casa",
    category: "Cocteleria",
    subCategory: "Margaritas",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 116,
    name: "Margarita Rústika",
    valueUnit: 17000,
    valueJug: 0,
    description: "José Cuervo, Triple Sec, zumo de limón, sirope de frutos amarillos, ahumada con clavos y canela, michelada con sal aromatizada de la casa",
    category: "Cocteleria",
    subCategory: "Margaritas",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 117,
    name: "Margarita de Mango Biche",
    valueUnit: 15000,
    valueJug: 0,
    description: "José Cuervo, Triple Sec, zumo de limón, mango biche y michelada con sal aromatizada de la casa",
    category: "Cocteleria",
    subCategory: "Margaritas Frappé",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 118,
    name: "Margarita de Lulo",
    valueUnit: 15000,
    valueJug: 0,
    description: "José Cuervo, Triple Sec, zumo de limon, lulo y michelada con sal aromatizada de la casa",
    category: "Cocteleria",
    subCategory: "Margaritas Frappé",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 119,
    name: "Margarita de Frutos Rojos",
    valueUnit: 16000,
    valueJug: 0,
    description: "José Cuervo, Triple Sec, zumo de limon, sirope de frutos rojos y michelada con sal aromatizada de la casa",
    category: "Cocteleria",
    subCategory: "Margaritas Frappé",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 120,
    name: "Mojito Tradicional",
    valueUnit: 14000,
    valueJug: 0,
    description: "Ron Blanco, limón tahití, azúcar y hierbabuena",
    category: "Cocteleria",
    subCategory: "Mojitos",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 121,
    name: "Mojito Martini",
    valueUnit: 14000,
    valueJug: 0,
    description: "Ron Blanco, limón tahití, azúcar y hierbabuena",
    category: "Cocteleria",
    subCategory: "Mojitos",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 122,
    name: "Mojiterona",
    valueUnit: 22000,
    valueJug: 0,
    description: "José Cuervo, coronita, sirope de frutos rojos, limón tahití, azúcar y hierbabuena",
    category: "Cocteleria",
    subCategory: "Mojitos",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 123,
    name: "Mojito Picante",
    valueUnit: 15000,
    valueJug: 0,
    description: "Ron Blanco. reducción de chiles, limón tahití, azúcar y hierbabuena",
    category: "Cocteleria",
    subCategory: "Mojitos",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 124,
    name: "Sangría Blanca",
    valueUnit: 18000,
    valueJug: 62000,
    description: "Vino Blanco, Brandy, zumo de naranja, manzana verde y canela en astilla",
    category: "Cocteleria",
    subCategory: "Sangrias",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 125,
    name: "Sangría Roja",
    valueUnit: 17000,
    valueJug: 60000,
    description: "Vino Tinto, Brandy, zumo de naranja, manzana roja y canela en astilla",
    category: "Cocteleria",
    subCategory: "Sangrias",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 126,
    name: "Gin Tonic de la Casa",
    valueUnit: 18000,
    valueJug: 0,
    description: "Gordon's, tonica, slash de pepino y/o rodajas de limón",
    category: "Cocteleria",
    subCategory: "Gin Tonic",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 127,
    name: "Gin Tonic Hendricks",
    valueUnit: 33000,
    valueJug: 0,
    description: "con tonica mil 976 ocean, slasjh de pepino y/o rodajas de limón",
    category: "Cocteleria",
    subCategory: "Gin Tonic",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 128,
    name: "Gin Tonic Beefeater",
    valueUnit: 27000,
    valueJug: 0,
    description: "con tonica mil 976 ocean, slasjh de pepino y/o rodajas de limón",
    category: "Cocteleria",
    subCategory: "Gin Tonic",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 129,
    name: "Copa de vino",
    valueUnit: 17000,
    valueJug: 0,
    description: "",
    category: "Cocteleria",
    subCategory: "Otros Cocteles",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 130,
    name: "Copa de vino caliente",
    valueUnit: 14000,
    valueJug: 0,
    description: "Vino tinto, Triple Sec, rodajas de limón y michelado con azúcar y canela",
    category: "Cocteleria",
    subCategory: "Otros Cocteles",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 131,
    name: "Dulce Primavera",
    valueUnit: 18000,
    valueJug: 0,
    description: "Gordon's, licor de Soho Lychee, Vino blanco, Sirope de frutos rojos, pepino, hierbabuena y lychee",
    category: "Cocteleria",
    subCategory: "Otros Cocteles",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 132,
    name: "Pasión Rosa",
    valueUnit: 13000,
    valueJug: 0,
    description: "Gordon's Absolut, sirope de frutos rojos y hierbabuena",
    category: "Cocteleria",
    subCategory: "Otros Cocteles",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 132,
    name: "Mut",
    valueUnit: 13000,
    valueJug: 0,
    description: "Black and White, Absolut, sirope de frutos rojos, zumo de limón y hierbabuena",
    category: "Cocteleria",
    subCategory: "Otros Cocteles",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 133,
    name: "Pasión Jager",
    valueUnit: 18000,
    valueJug: 0,
    description: "Jagermeister, Absolut, piña, pepino y zumo de limón",
    category: "Cocteleria",
    subCategory: "Otros Cocteles",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 134,
    name: "Piña Colada Rústika",
    valueUnit: 18000,
    valueJug: 0,
    description: "Crema de Whisky, Ron Blanco, crema de coco, crema d leche, piña, coco rayado y sirope de frutos rojos",
    category: "Cocteleria",
    subCategory: "Otros Cocteles",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 135,
    name: "Ron de Verano",
    valueUnit: 10000,
    valueJug: 0,
    description: "Ron Blanco, zumo de limón, maracuyá y piña",
    category: "Cocteleria",
    subCategory: "Otros Cocteles",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 136,
    name: "Whisky Sour",
    valueUnit: 13000,
    valueJug: 0,
    description: "Black and White. azúcar pulverizada, zumo de limón, clara de huevo y aromatizado con canela en astilla",
    category: "Cocteleria",
    subCategory: "Otros Cocteles",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 137,
    name: "Black and White",
    valueUnit: 5000,
    valueJug: 0,
    description: "",
    category: "Shots",
    subCategory: "Whisky",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 138,
    name: "Buchanans 12 años",
    valueUnit: 12000,
    valueJug: 0,
    description: "",
    category: "Shots",
    subCategory: "Whisky",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 139,
    name: "Jack Daniels",
    valueUnit: 13000,
    valueJug: 0,
    description: "",
    category: "Shots",
    subCategory: "Whisky",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 140,
    name: "Old Parr 12 años",
    valueUnit: 12000,
    valueJug: 0,
    description: "",
    category: "Shots",
    subCategory: "Whisky",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 141,
    name: "Red Label",
    valueUnit: 8000,
    valueJug: 0,
    description: "",
    category: "Shots",
    subCategory: "Whisky",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 142,
    name: "Viejo de Caldas 3 años",
    valueUnit: 5000,
    valueJug: 0,
    description: "",
    category: "Shots",
    subCategory: "Ron",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 143,
    name: "Bacardi Carta Blanca",
    valueUnit: 5000,
    valueJug: 0,
    description: "",
    category: "Shots",
    subCategory: "Ron",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 144,
    name: "Zacapa Ámbar 12 años",
    valueUnit: 12000,
    valueJug: 0,
    description: "",
    category: "Shots",
    subCategory: "Ron",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 145,
    name: "Parce 8 años",
    valueUnit: 18000,
    valueJug: 0,
    description: "",
    category: "Shots",
    subCategory: "Ron",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 146,
    name: "José Cuervo Reposado",
    valueUnit: 13000,
    valueJug: 0,
    description: "",
    category: "Shots",
    subCategory: "Tequila",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 147,
    name: "Don Julio Blanco",
    valueUnit: 17500,
    valueJug: 0,
    description: "",
    category: "Shots",
    subCategory: "Tequila",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 148,
    name: "3 Caballos",
    valueUnit: 6000,
    valueJug: 0,
    description: "",
    category: "Shots",
    subCategory: "Tequila",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 149,
    name: "Patrón XO Café",
    valueUnit: 13000,
    valueJug: 0,
    description: "",
    category: "Shots",
    subCategory: "Tequila",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 150,
    name: "Aguardiente Sin Azúcar",
    valueUnit: 4000,
    valueJug: 0,
    description: "",
    category: "Shots",
    subCategory: "Aguardiente",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 151,
    name: "Aguardiente de Manzanares",
    valueUnit: 5000,
    valueJug: 0,
    description: "",
    category: "Shots",
    subCategory: "Aguardiente",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 152,
    name: "Absoluct Vodka",
    valueUnit: 7000,
    valueJug: 0,
    description: "",
    category: "Shots",
    subCategory: "Otros Shots",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 153,
    name: "Baileys",
    valueUnit: 6000,
    valueJug: 0,
    description: "",
    category: "Shots",
    subCategory: "Otros Shots",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 154,
    name: "Brandy",
    valueUnit: 5000,
    valueJug: 0,
    description: "",
    category: "Shots",
    subCategory: "Otros Shots",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 155,
    name: "Jagermeistar",
    valueUnit: 9500,
    valueJug: 0,
    description: "",
    category: "Shots",
    subCategory: "Otros Shots",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 156,
    name: "Aguardiente Antioqueño Botella",
    valueUnit: 79000,
    valueJug: 0,
    description: "",
    category: "Licores",
    subCategory: "Licores",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 157,
    name: "Aguardiente Antioqueño Media",
    valueUnit: 44000,
    valueJug: 0,
    description: "",
    category: "Licores",
    subCategory: "Licores",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 158,
    name: "Aguardiente Amarillo Botella",
    valueUnit: 90000,
    valueJug: 0,
    description: "",
    category: "Licores",
    subCategory: "Licores",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 159,
    name: "Aguardiente Amarillo Media",
    valueUnit: 47000,
    valueJug: 0,
    description: "",
    category: "Licores",
    subCategory: "Licores",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 160,
    name: "Brandy Domeq Botella",
    valueUnit: 88000,
    valueJug: 0,
    description: "",
    category: "Licores",
    subCategory: "Licores",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 161,
    name: "Brandy Domeq Media",
    valueUnit: 48000,
    valueJug: 0,
    description: "",
    category: "Licores",
    subCategory: "Licores",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 162,
    name: "Ron Viejo de Caldas 3 años Botella",
    valueUnit: 88000,
    valueJug: 0,
    description: "",
    category: "Licores",
    subCategory: "Licores",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 163,
    name: "Ron Viejo de Caldas 3 años Media",
    valueUnit: 48000,
    valueJug: 0,
    description: "",
    category: "Licores",
    subCategory: "Licores",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 164,
    name: "Ron Viejo de Caldas 3 años Media",
    valueUnit: 180000,
    valueJug: 0,
    description: "",
    category: "Licores",
    subCategory: "Licores",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 165,
    name: "Tequila José Cuervo Reposado Botella",
    valueUnit: 0,
    valueJug: 0,
    description: "",
    category: "Licores",
    subCategory: "Licores",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 166,
    name: "Tequila 1800 Silver Botella",
    valueUnit: 285000,
    valueJug: 0,
    description: "",
    category: "Licores",
    subCategory: "Licores",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 167,
    name: "Tequila 1800 Reposado Botella",
    valueUnit: 275000,
    valueJug: 0,
    description: "",
    category: "Licores",
    subCategory: "Licores",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 168,
    name: "Tequila 3 Caballos",
    valueUnit: 155000,
    valueJug: 0,
    description: "",
    category: "Licores",
    subCategory: "Licores",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 169,
    name: "Vino Trapiche Botella",
    valueUnit: 74000,
    valueJug: 0,
    description: "",
    category: "Licores",
    subCategory: "Licores",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 170,
    name: "Whisky Black and White Botella",
    valueUnit: 86000,
    valueJug: 0,
    description: "",
    category: "Licores",
    subCategory: "Licores",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 171,
    name: "Whisky Buchanans 12 años Botella",
    valueUnit: 235000,
    valueJug: 0,
    description: "",
    category: "Licores",
    subCategory: "Licores",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 172,
    name: "Whisky Old Parr 12 años Botella",
    valueUnit: 215000,
    valueJug: 0,
    description: "",
    category: "Licores",
    subCategory: "Licores",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 172,
    name: "Whisky Old Parr 12 años Medio litro",
    valueUnit: 165000,
    valueJug: 0,
    description: "",
    category: "Licores",
    subCategory: "Licores",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 173,
    name: "Whisky Red label Botella",
    valueUnit: 120000,
    valueJug: 0,
    description: "",
    category: "Licores",
    subCategory: "Licores",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
}, {
    id: 174,
    name: "Whisky SomeThing Special Botella",
    valueUnit: 125000,
    valueJug: 0,
    description: "",
    category: "Licores",
    subCategory: "Licores",
    descuento: false,
    porcentaje: 0,
    newValue: 0,
    imageUrl: "https://picsum.photos/200/300"
},
]



export default menujson;